#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Cross-category overlap: which entities two departments have in common.

For each pair of categories, the number of shared entities (objects of
triples), their Jaccard index, and the relations through which they enter --
'English' shared through hasLanguage does not say the same thing as 'Stephen
King' through hasAuthor. The objects of hasMainCategory are excluded: they
are the department name itself, present on every product.

Reads out_final/<CAT>.kg; writes the LaTeX table and out_final/overlap.json.

    python analyze_overlap.py -o out_final [--category A --category B]
"""
import argparse
import io
import itertools
import json
import os
import sys
import time
from collections import defaultdict

RACINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, RACINE)
from archive_reader import set_output_dir, open_file, available_categories  # noqa: E402
EXCLUES = {"hasMainCategory"}
TAXO = "# taxonomie"


def log(msg):
    print("[%s] %s" % (time.strftime("%H:%M:%S"), msg), flush=True)


def entities_of(cat):
    """{(relation, object)} of the .kg of a category (out_final/ or archive),
    excluding the excluded relations and the taxonomy."""
    ens = set()
    dans_taxo = False
    with open_file(cat, ".kg") as fh:
        for ligne in fh:
            if ligne.startswith("# "):
                if ligne.startswith(TAXO):
                    dans_taxo = True
                continue
            if dans_taxo:
                continue
            parts = ligne.rstrip("\n").split("\t")
            if len(parts) != 3 or parts[1] in EXCLUES:
                continue
            ens.add((parts[1], parts[2]))
    return ens


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--category", action="append", default=[])
    ap.add_argument("--tex", default=os.path.join(RACINE, "paper", "tables", "overlap.tex"))
    args = ap.parse_args(argv)
    set_output_dir(args.out)

    cats = args.category or available_categories()
    if len(cats) < 2:
        sys.exit("at least two categories are required")

    # (relation, object) is kept to count per relation; the set of objects
    # alone is used for the Jaccard.
    par_cat = {}
    for c in cats:
        if open_file(c, ".kg") is None:
            log("%s: .kg missing, skipped" % c)
            continue
        log("%s: reading" % c)
        par_cat[c] = entities_of(c)
        log("%s: %s distinct (relation, entity)" % (c, format(len(par_cat[c]), ",")))
    cats = [c for c in cats if c in par_cat]
    objets = {c: {o for _r, o in e} for c, e in par_cat.items()}

    resultats = {"categories": cats, "paires": {}}
    for a, b in itertools.combinations(cats, 2):
        commun = objets[a] & objets[b]
        union = objets[a] | objets[b]
        par_rel = defaultdict(int)
        for r, o in par_cat[a]:
            if o in commun and (r, o) in par_cat[b]:
                par_rel[r] += 1
        top = sorted(par_rel.items(), key=lambda kv: -kv[1])[:6]
        resultats["paires"]["%s|%s" % (a, b)] = {
            "partagees": len(commun),
            "jaccard": round(len(commun) / max(1, len(union)), 5),
            "taille_a": len(objets[a]), "taille_b": len(objets[b]),
            "par_relation": top,
        }
    with io.open(os.path.join(args.out, "overlap.json"), "w", encoding="utf-8") as fh:
        json.dump(resultats, fh, ensure_ascii=False, indent=1)

    # --- LaTeX table: half matrix of Jaccard values, per thousand ---------
    court = {c: c.replace("_and_", " & ").replace("_", " ") for c in cats}
    abrev = {c: "".join(w[0] for w in court[c].replace("&", "").split())[:4] for c in cats}
    t = []
    a_ = t.append
    a_(r"% GENERATED BY analyze_overlap.py -- DO NOT EDIT BY HAND")
    a_(r"\begin{table}[t]")
    a_(r"\centering")
    a_(r"\caption{Cross-domain overlap: Jaccard index (\textperthousand) between the "
       r"entity sets of two categories, \texttt{hasMainCategory} excluded. Column "
       r"labels abbreviate the row names. The full matrix with counts per relation "
       r"is released with the data.}")
    a_(r"\label{tab:recouvrement}")
    a_(r"\setlength{\tabcolsep}{2.2pt}")
    a_(r"\scriptsize")
    a_(r"\begin{tabular}{l" + "r" * (len(cats) - 1) + "}")
    a_(r"\toprule")
    a_(" & " + " & ".join(abrev[c] for c in cats[1:]) + r" \\")
    a_(r"\midrule")
    for i, a in enumerate(cats[:-1]):
        cellules = []
        for j, b in enumerate(cats[1:], start=1):
            if j <= i:
                cellules.append("")
            else:
                cle = "%s|%s" % (a, b)
                cellules.append("%.1f" % (1000 * resultats["paires"][cle]["jaccard"]))
        a_(court[a].replace("&", r"\&") + " & " + " & ".join(cellules) + r" \\")
    a_(r"\bottomrule")
    a_(r"\end{tabular}")
    a_(r"\end{table}")
    os.makedirs(os.path.dirname(args.tex), exist_ok=True)
    io.open(args.tex, "w", encoding="utf-8").write("\n".join(t) + "\n")

    # --- macros for the tables ----------------------------------------------
    chiffres = os.path.join(RACINE, "paper", "tables", "numbers.tex")
    if os.path.exists(chiffres) and not args.category:
        cle, v = max(resultats["paires"].items(), key=lambda kv: kv[1]["jaccard"])
        pa, pb = cle.split("|")
        rel, n = v["par_relation"][0]
        nb_paires_10 = sum(1 for x in resultats["paires"].values() if x["jaccard"] >= 0.01)
        s = io.open(chiffres, encoding="utf-8").read()
        s = "\n".join(l for l in s.splitlines() if "Entites" not in l)
        s += ("\n\\newcommand{\\paireEntitesMax}{%s--%s}\n\\newcommand{\\jaccardEntitesMax}{%.1f}\n"
              "\\newcommand{\\nbEntitesPaireMax}{%s}\n\\newcommand{\\relEntitesPaireMax}{%s}\n"
              "\\newcommand{\\nbEntitesRelPaireMax}{%s}\n\\newcommand{\\nbPairesEntitesDix}{%d}\n"
              "\\newcommand{\\nbPairesEntites}{%d}\n"
              % (court[pa].replace("&", "\\&"), court[pb].replace("&", "\\&"), 1000 * v["jaccard"],
                 "{:,}".format(v["partagees"]).replace(",", "{,}"), rel.replace("_", "\\_"),
                 "{:,}".format(n).replace(",", "{,}"), nb_paires_10, len(resultats["paires"])))
        io.open(chiffres, "w", encoding="utf-8").write(s)

    # --- console summary ----------------------------------------------------
    log("most linked pairs:")
    for cle, v in sorted(resultats["paires"].items(), key=lambda kv: -kv[1]["jaccard"])[:8]:
        a, b = cle.split("|")
        rels = ", ".join("%s %s" % (r.replace("has", ""), format(n, ",")) for r, n in v["par_relation"][:3])
        print("  %-26s %-26s %8s shared  J=%.4f   %s"
              % (a, b, format(v["partagees"], ","), v["jaccard"], rels))
    log("written: %s and overlap.json" % args.tex)
    return 0


if __name__ == "__main__":
    sys.exit(main())
